services:
    # Compiler
    api_response.compiler.api_config: # Generated in ApiResponseExtension compile pass.
        class: MattJanssen\ApiResponseBundle\Compiler\ApiConfigCompiler
        public: false
        arguments:
            - "%api_response.defaults%"
            - "%api_response.paths%"

    # Subscriber
    api_response.subscriber.api_response:
        class: MattJanssen\ApiResponseBundle\Subscriber\ApiResponseSubscriber
        tags: [ { name: kernel.event_subscriber } ]
        arguments:
            - "@api_response.generator.api_response"
            - "@api_response.compiler.api_config"
            - "@logger"
            - "%kernel.debug%"

    # Factory
    api_response.factory.serializer_adapter:
        class: MattJanssen\ApiResponseBundle\Factory\SerializerAdapterFactory
        public: false
        arguments:
            - "@service_container"

    # Generator
    api_response.generator.api_response:
        class: MattJanssen\ApiResponseBundle\Generator\ApiResponseGenerator
        arguments:
            - "@request_stack"
            - "@api_response.compiler.api_config"
            - "@api_response.factory.serializer_adapter"
